---
title: "rgnparser"
author: "Scott Chamberlain"
date: "2021-01-21"
output:
  html_document:
    toc: true
    toc_float: true
    theme: readable
vignette: >
  %\VignetteIndexEntry{Introduction to rgnparser}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



rgnparser: Parse Scientific Names

An R interface to `gnparser` at https://github.com/gnames/gnparser

## Installation


```r
install.packages("rgnparser")
# OR
remotes::install_github("ropensci/rgnparser")
```


```r
library(rgnparser)
```

## Install gnparser

The command line tool written in Go, gnparser, is required to use this package.

If you want to install gnparser on your own, instructions can be found at the [gnparser repo][gnparser].

There is a helper function in **rgnparser** for downloading and installing gnparser on major
operating systems (macOS, Windows, Linux):


```r
rgnparser::install_gnparser()
```

It installs the latest gnparser version by default, but you can specify which 
version to install. You can also install gnparser outside of R yourself (see above).

## gn_version

gnparser version


```r
gn_version()
#> $version
#> [1] "v1.0.0"
#> 
#> $build
#> [1] "2021-01-19_14:45:28UTC"
```

## gn_debug

debug output


```r
gn_debug("Poa")
#> <rgnparser debug>
#> 
#> *** Complete Syntax Tree ***
#> SciName "Poa"
#>  Name "Poa"
#>   SingleName "Poa"
#>    NameUninomial "Poa"
#>     Uninomial "Poa"
#>      UninomialWord "Poa"
#>       CapWord "Poa"
#>        CapWord1 "Poa"
#>         NameUpperChar "P"
#>          UpperChar "P"
#>           UpperASCII "P"
#>         NameLowerChar "o"
#>          LowerChar "o"
#>           LowerASCII "o"
#>         NameLowerChar "a"
#>          LowerChar "a"
#>           LowerASCII "a"
#> 
#> *** Output Syntax Tree ***
#> SciName "Poa"
#>  Name "Poa"
#>   SingleName "Poa"
#>    Uninomial "Poa"
#>     UninomialWord "Poa"
#>  Tail ""
```

## gn_parse_tidy

output a data.frame with more minimal information


```r
x <- c("Quadrella steyermarkii (Standl.) Iltis &amp; Cornejo",
  "Parus major Linnaeus, 1788", "Helianthus annuus var. texanus")
gn_parse_tidy(x)
#> # A tibble: 3 x 9
#>   id    verbatim cardinality canonicalstem canonicalsimple canonicalfull
#>   <chr> <chr>          <dbl> <chr>         <chr>           <chr>        
#> 1 3e33… Quadrel…           2 Quadrella st… Quadrella stey… Quadrella st…
#> 2 e4e1… Parus m…           2 Parus maior   Parus major     Parus major  
#> 3 e571… Heliant…           3 Helianthus a… Helianthus ann… Helianthus a…
#> # … with 3 more variables: authorship <chr>, year <dbl>, quality <dbl>
```

It's pretty fast, thanks to gnparser of course


```r
n <- 10000L
# get random scientific names from taxize
spp <- taxize::names_list(rank = "species", size = n)
timed <- system.time(gn_parse_tidy(spp))
timed
#>    user  system elapsed 
#>   0.943   0.108   0.488
```

Just 0.488 sec for 10000 names

## gn_parse

output a list of lists with more detailed information


```r
x <- c("Quadrella steyermarkii (Standl.) Iltis &amp; Cornejo",
  "Parus major Linnaeus, 1788", "Helianthus annuus var. texanus")
gn_parse(x)
#> [[1]]
#> [[1]]$parsed
#> [1] TRUE
#> 
#> [[1]]$quality
#> [1] 3
#> 
#> [[1]]$qualityWarnings
#>   quality                           warning
#> 1       3 HTML tags or entities in the name
#> 
#> [[1]]$verbatim
#> [1] "Quadrella steyermarkii (Standl.) Iltis & Cornejo"
#> 
#> [[1]]$normalized
...
```

[gnparser]: https://github.com/gnames/gnparser
